//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int AdsId { get; set; }
        public int AdsetId { get; set; }
        public string AdsName { get; set; }
        public string LinkUrl { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ListNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual Adset Adset { get; set; }
    }
}
