//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public long AddressId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Complement { get; set; }
        public string AddressName { get; set; }
        public string Address1 { get; set; }
        public string Street { get; set; }
        public string PostalCode { get; set; }
        public int CountryId { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string Floor { get; set; }
        public string Remarks { get; set; }
        public long UserId { get; set; }
        public int TitleId { get; set; }
        public int CityId { get; set; }
        public string PhoneCountryCode { get; set; }
        public string MobilePhoneCountryCode { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
    }
}
