//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContentId { get; set; }
        public Nullable<int> ContentType { get; set; }
        public int CategoryId { get; set; }
        public string Topic { get; set; }
        public string ShortDetail { get; set; }
        public string Detail { get; set; }
        public string TextDetail { get; set; }
        public string FileName1 { get; set; }
        public string FileDescription1 { get; set; }
        public string FileName2 { get; set; }
        public string FileDescription2 { get; set; }
        public string FileName3 { get; set; }
        public string FileDescription3 { get; set; }
        public string FileName4 { get; set; }
        public string FileDescription4 { get; set; }
        public string FileName5 { get; set; }
        public string FileDescription5 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Private { get; set; }
        public Nullable<bool> AwayShow { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
