//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Items = new HashSet<Item>();
            this.TeeSheets = new HashSet<TeeSheet>();
        }
    
        public int CourseId { get; set; }
        public int CourseTypeId { get; set; }
        public long SiteId { get; set; }
        public string CourseName { get; set; }
        public string CourseDesc { get; set; }
        public Nullable<int> Holes { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> DefaultPrice { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<short> Duration { get; set; }
        public Nullable<long> ExternalId { get; set; }
        public Nullable<int> Par { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<bool> OnlineBookingEnabled { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        public virtual Site Site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeeSheet> TeeSheets { get; set; }
    }
}
