//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditcardassociation
    {
        public int CardassociationsId { get; set; }
        public string CardassociationsType { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
