//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int CustomerId { get; set; }
        public string PersonalAddress { get; set; }
        public string PersonalCity { get; set; }
        public string PersonalPostalCode { get; set; }
        public int PersonalCountryId { get; set; }
        public string PersonalPhone { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessPostalCode { get; set; }
        public int BusinessCountryId { get; set; }
        public string BusinessPhone { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
    }
}
