//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLGCardStyle
    {
        public long CardStyleId { get; set; }
        public long ItemId { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> ListNo { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
