//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLGCardBalance
    {
        public int Id { get; set; }
        public int DLGCardId { get; set; }
        public long UserId { get; set; }
        public Nullable<int> ActionType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual DLGCard DLGCard { get; set; }
        public virtual User User { get; set; }
    }
}
