//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLGEntities : DbContext
    {
        public DLGEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Adset> Adsets { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<CouponGroup> CouponGroups { get; set; }
        public virtual DbSet<CourseType> CourseTypes { get; set; }
        public virtual DbSet<Creditcardassociation> Creditcardassociations { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerCreditCard> CustomerCreditCards { get; set; }
        public virtual DbSet<DLGCard> DLGCards { get; set; }
        public virtual DbSet<DLGCardBalance> DLGCardBalances { get; set; }
        public virtual DbSet<DLGCardStyle> DLGCardStyles { get; set; }
        public virtual DbSet<EmailAccount> EmailAccounts { get; set; }
        public virtual DbSet<EmailingAttachment> EmailingAttachments { get; set; }
        public virtual DbSet<EmailLog> EmailLogs { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<EmailTemplateAttachment> EmailTemplateAttachments { get; set; }
        public virtual DbSet<EmailTemplateLang> EmailTemplateLangs { get; set; }
        public virtual DbSet<EmailTemplateVariable> EmailTemplateVariables { get; set; }
        public virtual DbSet<EmailTracking> EmailTrackings { get; set; }
        public virtual DbSet<EmailUnsubscription> EmailUnsubscriptions { get; set; }
        public virtual DbSet<GolfBrand> GolfBrands { get; set; }
        public virtual DbSet<Impressum> Impressums { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<InterestLang> InterestLangs { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemChoice> ItemChoices { get; set; }
        public virtual DbSet<ItemConversionTracking> ItemConversionTrackings { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<ItemLang> ItemLangs { get; set; }
        public virtual DbSet<ItemModifier> ItemModifiers { get; set; }
        public virtual DbSet<ItemPosition> ItemPositions { get; set; }
        public virtual DbSet<ItemReview> ItemReviews { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<MailingList> MailingLists { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Modifier> Modifiers { get; set; }
        public virtual DbSet<ModifierChoice> ModifierChoices { get; set; }
        public virtual DbSet<ModifierChoiceLang> ModifierChoiceLangs { get; set; }
        public virtual DbSet<ModifierLang> ModifierLangs { get; set; }
        public virtual DbSet<NetMessageCampaign> NetMessageCampaigns { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<ReservationAPI> ReservationAPIs { get; set; }
        public virtual DbSet<RestaurantProductCategory> RestaurantProductCategories { get; set; }
        public virtual DbSet<RestaurantSupplier> RestaurantSuppliers { get; set; }
        public virtual DbSet<z> z { get; set; }
        public virtual DbSet<ShippingTypeLang> ShippingTypeLangs { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SiteCentralLineSEO> SiteCentralLineSEOs { get; set; }
        public virtual DbSet<SiteCommercialFollowUp> SiteCommercialFollowUps { get; set; }
        public virtual DbSet<SiteCommunication> SiteCommunications { get; set; }
        public virtual DbSet<SiteEvent> SiteEvents { get; set; }
        public virtual DbSet<SiteFinancial> SiteFinancials { get; set; }
        public virtual DbSet<SiteImage> SiteImages { get; set; }
        public virtual DbSet<SiteLang> SiteLangs { get; set; }
        public virtual DbSet<SiteRestaurantProductCategory> SiteRestaurantProductCategories { get; set; }
        public virtual DbSet<SiteRestaurantSupplier> SiteRestaurantSuppliers { get; set; }
        public virtual DbSet<SiteReview> SiteReviews { get; set; }
        public virtual DbSet<SlideImage> SlideImages { get; set; }
        public virtual DbSet<SponsorEmail> SponsorEmails { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TeeSheet> TeeSheets { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<TitleLang> TitleLangs { get; set; }
        public virtual DbSet<TopNavLink> TopNavLinks { get; set; }
        public virtual DbSet<UnsubscribeReason> UnsubscribeReasons { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserMessageAttached> UserMessageAttacheds { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<VariationHD> VariationHDs { get; set; }
        public virtual DbSet<WebContent> WebContents { get; set; }
        public virtual DbSet<EmailingList> EmailingLists { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CustomerTypeLang> CustomerTypeLangs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ItemPrice> ItemPrices { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<CustomerType> CustomerTypes { get; set; }
        public virtual DbSet<NetmessageReport> NetmessageReports { get; set; }
        public virtual DbSet<NetmessageReportRecord> NetmessageReportRecords { get; set; }
        public virtual DbSet<Emailing> Emailings { get; set; }
        public virtual DbSet<EmailQue> EmailQues { get; set; }
    }
}
