//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTracking
    {
        public long EmailTrackingId { get; set; }
        public long CampaignId { get; set; }
        public long EmailQueId { get; set; }
        public string Action { get; set; }
        public string Value { get; set; }
        public string IPAddress { get; set; }
        public string Browser { get; set; }
        public string Platform { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Emailing Emailing { get; set; }
        public virtual EmailQue EmailQue { get; set; }
    }
}
