//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int Id { get; set; }
        public long EmailQueId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Resending { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string ReturnMessage { get; set; }
    
        public virtual EmailQue EmailQue { get; set; }
    }
}
