//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAccount
    {
        public long EmailAccountId { get; set; }
        public string EmailAccountName { get; set; }
        public string Host { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> ConnectionType { get; set; }
        public Nullable<bool> IsTrackingOpenMail { get; set; }
        public Nullable<bool> IsTrackingClick { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
