//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailQue()
        {
            this.EmailLogs = new HashSet<EmailLog>();
            this.EmailTrackings = new HashSet<EmailTracking>();
        }
    
        public long EmailQueId { get; set; }
        public long EmailId { get; set; }
        public long CustomerId { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<bool> IsError { get; set; }
        public string ReturnMessage { get; set; }
        public Nullable<int> Resent { get; set; }
        public Nullable<bool> IsOpenMail { get; set; }
        public Nullable<bool> IsClickLink { get; set; }
        public byte[] HtmlDetail { get; set; }
        public byte[] TextDetail { get; set; }
        public Nullable<bool> IsUnsubscribe { get; set; }
        public string UnsubscribeMailTo { get; set; }
        public string UnsubscribeUrl { get; set; }
        public Nullable<bool> IsBounced { get; set; }
        public Nullable<long> NetMessageCampaignId { get; set; }
        public Nullable<System.DateTime> ScheduleDateTime { get; set; }
    
        public virtual Emailing Emailing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailTracking> EmailTrackings { get; set; }
    }
}
