//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplateLang
    {
        public int TemplateId { get; set; }
        public int LangId { get; set; }
        public string TemplateName { get; set; }
        public string Description { get; set; }
        public string Subject { get; set; }
        public byte[] HtmlDetail { get; set; }
        public string TextDetail { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
    }
}
