//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplateVariable
    {
        public int VariableId { get; set; }
        public string VariableName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ListNo { get; set; }
    }
}
