//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailingAttachment
    {
        public long EmailingAttachmentId { get; set; }
        public Nullable<long> EmailId { get; set; }
        public string FileName { get; set; }
        public string BaseName { get; set; }
        public string FileExtension { get; set; }
        public string FilePath { get; set; }
    
        public virtual Emailing Emailing { get; set; }
    }
}
