//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestLang
    {
        public int InterestId { get; set; }
        public int LangId { get; set; }
        public string InterestName { get; set; }
        public string InterestDesc { get; set; }
    
        public virtual Interest Interest { get; set; }
        public virtual Language Language { get; set; }
    }
}
