//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemConversionTracking
    {
        public long ItemId { get; set; }
        public string TrackingCodeViewContent { get; set; }
        public string TrackingCodeAddToCart { get; set; }
        public string TrackingCodeInitialCheckout { get; set; }
        public string TrackingCodePurchase { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
