//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLang
    {
        public long ItemId { get; set; }
        public int LangId { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public string ItemShortDesc { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TrainingArea { get; set; }
        public string Accommodation { get; set; }
        public string InvoiceName { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Language Language { get; set; }
    }
}
