//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.DLGCards = new HashSet<DLGCard>();
            this.DLGCardStyles = new HashSet<DLGCardStyle>();
            this.ItemChoices = new HashSet<ItemChoice>();
            this.ItemImages = new HashSet<ItemImage>();
            this.ItemLangs = new HashSet<ItemLang>();
            this.ItemModifiers = new HashSet<ItemModifier>();
            this.ItemReviews = new HashSet<ItemReview>();
            this.OrderItems = new HashSet<OrderItem>();
            this.TeeSheets = new HashSet<TeeSheet>();
            this.CouponGroups = new HashSet<CouponGroup>();
            this.ItemPrices = new HashSet<ItemPrice>();
        }
    
        public long ItemId { get; set; }
        public int CategoryId { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemCode { get; set; }
        public string ItemSlug { get; set; }
        public Nullable<int> Shape { get; set; }
        public Nullable<int> Genre { get; set; }
        public Nullable<int> Dexterity { get; set; }
        public Nullable<int> Shaft { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public long UserId { get; set; }
        public long SiteId { get; set; }
        public decimal Price { get; set; }
        public decimal OldPrice { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<bool> IsAllowReview { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public int TaxId { get; set; }
        public Nullable<int> UnitInStock { get; set; }
        public Nullable<bool> IsShowOnHomepage { get; set; }
        public Nullable<System.DateTime> AvailableStartDate { get; set; }
        public Nullable<System.DateTime> AvailableEndDate { get; set; }
        public int SupplierId { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> PublishStartDate { get; set; }
        public Nullable<System.DateTime> PublishEndDate { get; set; }
        public Nullable<bool> IncludePractice { get; set; }
        public Nullable<bool> IncludeAccommodation { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public int ShippingTimeMin { get; set; }
        public int ShippingTimeMax { get; set; }
        public Nullable<bool> CanReturn { get; set; }
        public Nullable<int> RefundWithIn { get; set; }
        public Nullable<int> ShippingTypeId { get; set; }
        public int BrandId { get; set; }
        public string Size { get; set; }
        public Nullable<bool> PromotionStatusId { get; set; }
        public Nullable<bool> IsUserCanSelectDate { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public Nullable<bool> IsDiscountCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DLGCard> DLGCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DLGCardStyle> DLGCardStyles { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Site Site { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Tax Tax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemChoice> ItemChoices { get; set; }
        public virtual ItemConversionTracking ItemConversionTracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemImage> ItemImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLang> ItemLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemModifier> ItemModifiers { get; set; }
        public virtual ItemPosition ItemPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemReview> ItemReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeeSheet> TeeSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponGroup> CouponGroups { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPrice> ItemPrices { get; set; }
        public virtual Course Course { get; set; }
    }
}
