//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingList
    {
        public int MailingListId { get; set; }
        public string MailingListName { get; set; }
        public Nullable<bool> Active { get; set; }
        public long SiteId { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
