//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int MenuItemId { get; set; }
        public int MenuId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string MenuType { get; set; }
        public string MenuTitle { get; set; }
        public string MenuValue { get; set; }
        public Nullable<bool> IsOpenNewWindow { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
