//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModifierChoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModifierChoice()
        {
            this.ItemChoices = new HashSet<ItemChoice>();
            this.ModifierChoiceLangs = new HashSet<ModifierChoiceLang>();
        }
    
        public int ChoiceId { get; set; }
        public int ModifierId { get; set; }
        public string ChoiceName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public long UserId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemChoice> ItemChoices { get; set; }
        public virtual Modifier Modifier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModifierChoiceLang> ModifierChoiceLangs { get; set; }
        public virtual User User { get; set; }
    }
}
