//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCentralLineSEO
    {
        public long SiteId { get; set; }
        public int FiscalYear { get; set; }
        public Nullable<bool> InvoiceEntryField { get; set; }
        public Nullable<bool> InvoiceEntryRestaurant { get; set; }
        public Nullable<bool> InvoiceEntryOther { get; set; }
        public Nullable<System.DateTime> InformationRequestDate { get; set; }
        public string BeingCalledByProductResp { get; set; }
        public string InformationRequestOther { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
