//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteEvent
    {
        public long SiteId { get; set; }
        public int FiscalYear { get; set; }
        public Nullable<bool> HasChallenge { get; set; }
        public Nullable<System.DateTime> ChallengeDate { get; set; }
        public Nullable<bool> HasPingClassicTour { get; set; }
        public Nullable<System.DateTime> PingClassicTourDate { get; set; }
        public Nullable<bool> HasCongressOwner { get; set; }
        public Nullable<bool> HasCongressManager { get; set; }
        public Nullable<bool> HasCongressGreenKeeper { get; set; }
        public Nullable<bool> HasCongressRestaurateur { get; set; }
        public Nullable<bool> HasCongressRespProshop { get; set; }
        public Nullable<bool> HasShowroomManager { get; set; }
        public Nullable<bool> HasShowroomRespProshop { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> HasClubMedThophy { get; set; }
        public Nullable<System.DateTime> ClubMedThophyDate { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
