//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCommunication
    {
        public long SiteId { get; set; }
        public int FiscalYear { get; set; }
        public Nullable<bool> UsePageGuide { get; set; }
        public Nullable<bool> UsePageSite { get; set; }
        public Nullable<bool> UseStaysOffers { get; set; }
        public string NewslettersOrder { get; set; }
        public Nullable<System.DateTime> NewslettersSendDate { get; set; }
        public string NewslettersSendDetail { get; set; }
        public Nullable<bool> UseTerminal { get; set; }
        public Nullable<bool> UseShowBooklet { get; set; }
        public Nullable<bool> UseLogoOnSite { get; set; }
        public Nullable<bool> UseTotem { get; set; }
        public Nullable<bool> UseGuideFlyers { get; set; }
        public Nullable<bool> UseSheet { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
