//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteRestaurantSupplier
    {
        public long SiteId { get; set; }
        public long RestaurantSupplierId { get; set; }
        public int FiscalYear { get; set; }
    
        public virtual RestaurantSupplier RestaurantSupplier { get; set; }
        public virtual Site Site { get; set; }
    }
}
