//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeeSheet
    {
        public long TeeSheetId { get; set; }
        public int CourseId { get; set; }
        public Nullable<short> TeeSheetDay { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> TeeSheetDate { get; set; }
        public long ItemId { get; set; }
        public Nullable<int> PreBookingDays { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Course Course { get; set; }
    }
}
