//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessageAttached
    {
        public long AttachedId { get; set; }
        public long MessageId { get; set; }
        public string BaseFileName { get; set; }
        public string FileExtension { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual UserMessage UserMessage { get; set; }
    }
}
