//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DansLesGolfs.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebContent
    {
        public long ContentId { get; set; }
        public string ContentCategory { get; set; }
        public string ContentKey { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    }
}
