IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Site' AND COLUMN_NAME = 'PrimaBookerId')
BEGIN
ALTER TABLE [Site] DROP COLUMN PrimaBookerId
END

IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Site' AND COLUMN_NAME = 'PrimaServerUrl')
BEGIN
ALTER TABLE [Site] DROP COLUMN PrimaServerUrl
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Site' AND COLUMN_NAME = 'PrimaAPIKey')
BEGIN
ALTER TABLE [Site] ADD PrimaAPIKey nvarchar(50) NULL
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Site' AND COLUMN_NAME = 'PrimaClubKey')
BEGIN
ALTER TABLE [Site] ADD PrimaClubKey nvarchar(50) NULL
END